name = "my-landing-page"
main = "dist/index.html"
compatibility_date = "2024-03-20"

[vars]
VITE_SUPABASE_URL = "your-supabase-url"
VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[site]
bucket = "./dist"

[build]
command = "pnpm run build" 