name = "my-landing-page-worker"
main = "src/worker.ts"
compatibility_date = "2024-03-20"

[vars]
VITE_SUPABASE_URL = "your-supabase-url"
VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[build]
command = "npm run build"
cwd = "."

[site]
bucket = "./dist" 